import { promises as fs } from 'fs'
import path from 'path'
import { exec } from 'child_process'
import { promisify } from 'util'
import { app } from 'electron'
import log from 'electron-log'

const execAsync = promisify(exec)

const SHIM_MARKER = 'GLIT_CLI_SHIM_V1'
const INSTALL_PATH = '/usr/local/bin/glit'

export interface CliInstallStatus {
  /** macOS-packaged app — feature is available */
  available: boolean
  /** Is a Glit-generated shim currently at INSTALL_PATH */
  installed: boolean
  /** Where the shim is (or would be) written */
  path: string
}

function isAvailable(): boolean {
  return process.platform === 'darwin' && app.isPackaged
}

function buildShimContent(): string {
  const exe = app.getPath('exe')
  return `#!/bin/sh
# ${SHIM_MARKER} — generated by Glit, do not edit by hand
GLIT_BIN=${shellQuoteDouble(exe)}
if [ ! -x "$GLIT_BIN" ]; then
  echo "Glit not found at $GLIT_BIN. Reinstall the CLI from Glit > Settings." >&2
  exit 1
fi
TARGET="\${1:-$PWD}"
nohup "$GLIT_BIN" "$TARGET" >/dev/null 2>&1 &
disown 2>/dev/null || true
`
}

function shellQuoteDouble(s: string): string {
  // For embedding inside a `"..."` shell string. Escape \, $, `, and ".
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$').replace(/`/g, '\\`')}"`
}

function shellQuoteSingle(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`
}

export async function getCliInstallStatus(): Promise<CliInstallStatus> {
  const status: CliInstallStatus = {
    available: isAvailable(),
    installed: false,
    path: INSTALL_PATH,
  }
  if (!status.available) return status
  try {
    const content = await fs.readFile(INSTALL_PATH, 'utf-8')
    status.installed = content.includes(SHIM_MARKER)
  } catch {
    status.installed = false
  }
  return status
}

async function writeWithAdmin(content: string, target: string): Promise<void> {
  const tmp = path.join(app.getPath('temp'), `glit-shim-${Date.now()}.sh`)
  await fs.writeFile(tmp, content, { mode: 0o755 })
  try {
    const targetDir = path.dirname(target)
    const inner = `mkdir -p ${shellQuoteSingle(targetDir)} && /bin/cp -f ${shellQuoteSingle(tmp)} ${shellQuoteSingle(target)} && /bin/chmod 755 ${shellQuoteSingle(target)}`
    const script = `do shell script "${inner.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}" with administrator privileges`
    await execAsync(`osascript -e ${shellQuoteSingle(script)}`)
  } finally {
    await fs.unlink(tmp).catch(() => {})
  }
}

export async function installCli(): Promise<{ success: boolean; path?: string; error?: string }> {
  if (!isAvailable()) {
    return { success: false, error: 'CLI install is only supported on packaged macOS builds' }
  }
  const content = buildShimContent()
  try {
    await fs.mkdir(path.dirname(INSTALL_PATH), { recursive: true })
    await fs.writeFile(INSTALL_PATH, content, { mode: 0o755 })
    log.info(`CLI installed at ${INSTALL_PATH}`)
    return { success: true, path: INSTALL_PATH }
  } catch (err) {
    log.info(`Direct write to ${INSTALL_PATH} failed (${String(err)}), retrying with admin privileges`)
  }
  try {
    await writeWithAdmin(content, INSTALL_PATH)
    log.info(`CLI installed at ${INSTALL_PATH} via admin`)
    return { success: true, path: INSTALL_PATH }
  } catch (err) {
    log.error('CLI install failed:', err)
    return { success: false, error: String(err) }
  }
}

export async function uninstallCli(): Promise<{ success: boolean; error?: string }> {
  if (!isAvailable()) {
    return { success: false, error: 'CLI uninstall is only supported on packaged macOS builds' }
  }
  const status = await getCliInstallStatus()
  if (!status.installed) return { success: true }
  try {
    await fs.unlink(INSTALL_PATH)
    return { success: true }
  } catch (err) {
    log.info(`Direct unlink of ${INSTALL_PATH} failed (${String(err)}), retrying with admin privileges`)
  }
  try {
    const script = `do shell script "/bin/rm -f ${shellQuoteSingle(INSTALL_PATH)}" with administrator privileges`
    await execAsync(`osascript -e ${shellQuoteSingle(script)}`)
    return { success: true }
  } catch (err) {
    log.error('CLI uninstall failed:', err)
    return { success: false, error: String(err) }
  }
}
